name: Release

on: push

jobs:
  release:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, 'CI: push release')
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: npx conventional-github-releaser -p angular
        env:
          CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{secrets.GITHUB_TOKEN}}
